using BiomeExpansion.Content.Tiles.Biome;
using BiomeExpansion.Content.Tiles.Plants;
using BiomeExpansion.Content.Tiles.Sands;
using BiomeExpansion.Content.Tiles.Stones;
using BiomeExpansion.Content.Walls;
using BiomeExpansion.Core.Generation;
using BiomeExpansion.Helpers;
using Terraria;
using Terraria.IO;
using Terraria.ModLoader;
using Terraria.WorldBuilding;

namespace BiomeExpansion.Common.GenPasses;

public class InfectedMushroomSurfaceGenPass(string name, double loadWeight) : GenPass(name, loadWeight)
{
    protected override void ApplyPass(GenerationProgress progress, GameConfiguration configuration)
    { 
        progress.Message = "Generating Surface Infected Mushroom biome...";
        var surfaceBiomeBuilder = GenerationHelper.CreateSurfaceBiomeBuilder()
            .Biome(BEBiome.InfectedMushroomSurface)
            .BiomePlacer(GenerationHelper.RectangleBiomePlacer)
            .TilesToKill([TileID.SeaOats])
            .Width(500)
            .Height(20)
            .IsNearEvil();
        if (!WorldGen.crimson)
        {
            surfaceBiomeBuilder = surfaceBiomeBuilder
                .TileGenerationStep()
                    .TileType(ModContent.TileType<InfectedMushroomDirt>())
                    .TilePlacer(GenerationHelper.DirtTilePlacer)
                    .AndSurface()
                .TileGenerationStep()
                    .TileType(ModContent.TileType<CrimsonInfectedMushroomGrass>())
                    .TilePlacer(GenerationHelper.GrassTilePlacer)
                    .AdditionalTileTypes([(ushort)ModContent.TileType<InfectedMushroomDirt>()])
                    .AndSurface()
                .TileGenerationStep()
                    .TileType(ModContent.TileType<CrimsonInfectedMushroomStone>())
                    .TilePlacer(GenerationHelper.StoneTilePlacer)
                    .AndSurface()
                .TileGenerationStep()
                    .TileType(ModContent.TileType<CrimsonInfectedMushroomSand>())
                    .TilePlacer(GenerationHelper.SandTilePlacer)
                    .AndSurface()
                .TileGenerationStep()
                    .TileType(ModContent.TileType<CrimsonInfectedMushroomHardenedSand>())
                    .TilePlacer(GenerationHelper.SandstoneTilePlacer)
                    .AndSurface()
                .WallGenerationStep()
                    .WallType(ModContent.WallType<CrimsonInfectedMushroomSandWall>())
                    .WallPlacer(GenerationHelper.SimpleWallPlacer)
                    .ReplacedWalls([WallID.Sandstone, WallID.CorruptSandstone])
                    .AndSurface()
                .WallGenerationStep()
                    .WallType(ModContent.WallType<CrimsonInfectedMushroomGrassWall>())
                    .WallPlacer(GenerationHelper.SimpleWallPlacer)
                    .ReplacedWalls(BiomeHelper.GrassWalls)
                    .HighPriorityWalls([ModContent.WallType<CrimsonInfectedMushroomSandWall>()])
                    .AndSurface()
                .WallGenerationStep()
                    .WallType(ModContent.WallType<CrimsonInfectedMushroomStoneWall>())
                    .WallPlacer(GenerationHelper.SimpleWallPlacer)
                    .HighPriorityWalls([ModContent.WallType<CrimsonInfectedMushroomSandWall>(), ModContent.WallType<CrimsonInfectedMushroomGrassWall>()])
                    .AndSurface()
                .GroundDecorationGenerationStep()
                    .TileType(ModContent.TileType<CrimsonInfectedMushroomVines>())
                    .Rarity(2)
                    .DecorationPlacer(GenerationHelper.VinePlacer)
                    .AndSurface()
                .GroundDecorationGenerationStep()
                    .TileType(ModContent.TileType<GiantDeadCrimsonInfectedMushroom>())
                    .DecorationPlacer(GenerationHelper.SimpleDecorationPlacer)
                    .FrameCount(5)
                    .AndSurface()
                .GroundDecorationGenerationStep()
                    .TileType(ModContent.TileType<CrimsonInfectedMushroomLyingStem>())
                    .Rarity(50)
                    .DecorationPlacer(GenerationHelper.SimpleDecorationPlacer)
                    .AndSurface()
                .GroundDecorationGenerationStep()
                    .TileType(ModContent.TileType<CrimsonInfectedMushroomRock>())
                    .Rarity(50)
                    .DecorationPlacer(GenerationHelper.SimpleDecorationPlacer)
                    .AndSurface()
                .GroundDecorationGenerationStep()
                    .TileType(ModContent.TileType<CrimsonInfectedMushroomOats>())
                    .Rarity(15)
                    .DecorationPlacer(GenerationHelper.SeaOatsPlacer)
                    .AndSurface()
                .GroundDecorationGenerationStep()
                    .TileType(ModContent.TileType<CrimsonInfectedSmallMushroom>())
                    .Rarity(3)
                    .DecorationPlacer(GenerationHelper.SimplePlantPlacer)
                    .FrameCount(5)
                    .AndSurface()
                .GroundDecorationGenerationStep()
                    .TileType(ModContent.TileType<CrimsonInfectedMushroomTallGrass>())
                    .Rarity(2)
                    .DecorationPlacer(GenerationHelper.SimplePlantPlacer)
                    .FrameCount(9)
                    .AndSurface();
        }
        else 
        {
            surfaceBiomeBuilder = surfaceBiomeBuilder
                .TileGenerationStep()
                    .TileType(ModContent.TileType<InfectedMushroomDirt>())
                    .TilePlacer(GenerationHelper.DirtTilePlacer)
                    .AndSurface()
                .TileGenerationStep()
                    .TileType(ModContent.TileType<CorruptionInfectedMushroomGrass>())
                    .TilePlacer(GenerationHelper.GrassTilePlacer)
                    .AdditionalTileTypes([(ushort)ModContent.TileType<InfectedMushroomDirt>()])
                    .AndSurface()
                .TileGenerationStep()
                    .TileType(ModContent.TileType<CorruptionInfectedMushroomStone>())
                    .TilePlacer(GenerationHelper.StoneTilePlacer)
                    .AndSurface()
                .TileGenerationStep()
                    .TileType(ModContent.TileType<CorruptionInfectedMushroomSand>())
                    .TilePlacer(GenerationHelper.SandTilePlacer)
                    .AndSurface()
                .TileGenerationStep()
                    .TileType(ModContent.TileType<CorruptionInfectedMushroomHardenedSand>())
                    .TilePlacer(GenerationHelper.SandstoneTilePlacer)
                    .AndSurface()
                .WallGenerationStep()
                    .WallType(ModContent.WallType<CorruptionInfectedMushroomSandWall>())
                    .WallPlacer(GenerationHelper.SimpleWallPlacer)
                    .ReplacedWalls([WallID.Sandstone, WallID.CrimsonSandstone])
                    .AndSurface()
                .WallGenerationStep()
                    .WallType(ModContent.WallType<CorruptionInfectedMushroomGrassWall>())
                    .WallPlacer(GenerationHelper.SimpleWallPlacer)
                    .ReplacedWalls(BiomeHelper.GrassWalls)
                    .HighPriorityWalls([ModContent.WallType<CorruptionInfectedMushroomSandWall>()])
                    .AndSurface()
                .WallGenerationStep()
                    .WallType(ModContent.WallType<CorruptionInfectedMushroomStoneWall>())
                    .WallPlacer(GenerationHelper.SimpleWallPlacer)
                    .HighPriorityWalls([ModContent.WallType<CorruptionInfectedMushroomSandWall>(), ModContent.WallType<CorruptionInfectedMushroomGrassWall>()])
                    .AndSurface()
                .GroundDecorationGenerationStep()
                    .TileType(ModContent.TileType<CorruptionInfectedMushroomVines>())
                    .Rarity(2)
                    .DecorationPlacer(GenerationHelper.VinePlacer)
                    .AndSurface()
                .GroundDecorationGenerationStep()
                    .TileType(ModContent.TileType<GiantDeadCorruptionInfectedMushroom>())
                    .DecorationPlacer(GenerationHelper.SimpleDecorationPlacer)
                    .FrameCount(5)
                    .AndSurface()
                .GroundDecorationGenerationStep()
                    .TileType(ModContent.TileType<CorruptionInfectedMushroomLyingStem>())
                    .Rarity(50)
                    .DecorationPlacer(GenerationHelper.SimpleDecorationPlacer)
                    .AndSurface()
                .GroundDecorationGenerationStep()
                    .TileType(ModContent.TileType<CorruptionInfectedMushroomRock>())
                    .Rarity(50)
                    .DecorationPlacer(GenerationHelper.SimpleDecorationPlacer)
                    .AndSurface()
                .GroundDecorationGenerationStep()
                    .TileType(ModContent.TileType<CorruptionInfectedMushroomOats>())
                    .Rarity(15)
                    .DecorationPlacer(GenerationHelper.SeaOatsPlacer)
                    .AndSurface()
                .GroundDecorationGenerationStep()
                    .TileType(ModContent.TileType<CorruptionInfectedSmallMushroom>())
                    .Rarity(3)
                    .DecorationPlacer(GenerationHelper.SimplePlantPlacer)
                    .FrameCount(5)
                    .AndSurface()
                .GroundDecorationGenerationStep()
                    .TileType(ModContent.TileType<CorruptionInfectedMushroomTallGrass>())
                    .Rarity(2)
                    .DecorationPlacer(GenerationHelper.SimplePlantPlacer)
                    .FrameCount(9)
                    .AndSurface();
        }
        
        surfaceBiomeBuilder.Generate();
    }
}